CREATE TABLE locations (
    id INT NOT NULL AUTO_INCREMENT,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    title VARCHAR(64),
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE notes (
    id INT NOT NULL AUTO_INCREMENT,
    location_id INT,
    text TEXT NOT NULL,
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(128),
    added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
